# ~/.config/starship.toml

# Use custom format
format = """
$status$cmd_duration

[┌───────────────────>](bold green)
[│](bold green) $sudo$username$hostname
[│](bold green) $package$directory$git_branch$git_status 
[└─>](bold green) """

right_format = """
$battery$memory_usage$localip
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = true

[directory]
truncation_length = 100
truncation_symbol = "…/"

[[battery.display]]
threshold = 150
style = "bold blue"

[cmd_duration]
min_time = 0
format = "took [$duration](bold yellow)"

[localip]
ssh_only = false
format = "@[$localipv4]($style) "
disabled = false
style = "bold yellow"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"
format = "[${ram} ~${ram_pct}](bold green) "

[git_branch]
truncation_length = 60
truncation_symbol = "~"

[status]
style = "fg:blue"
success_symbol = "🟢 SUCCESS"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = "bold green"
symbol = "💻 "
disabled = false
format = "[$symbol]($style)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "on [$hostname](bold green) [$ssh_symbol](bold blue)"
trim_at = ".companyname.com"
disabled = false
